export const MESSAGE = {
    ROLE: "Role fetch",
    ROLE_NOT: "Role does not found",
    ROLE_DELETE: "Role has been deleted",
    ROLE_UPDATE: "Role has been updated",
    ROLE_NOT_UPDATE: "Role does not update",
    ROLE_ADD: "Role has been created",
    ROLE_DUPLICATE: "Role already exit",

    USER: "User fetch",
    USER_NOT: "User does not found",
    USER_NOT_LOGIN: "User not login",
    USER_DELETE: "User has been deleted",
    USER_UPDATE: "User has been updated",
    USER_ERROR_UPDATE: "User does not update",
    USER_DUPLICATE: "Email already exit",
    USER_REGISTER: "User has been created",
    USER_ERROR_REGISTER: "User can not register",
    USER_LOGIN: "User login succssfully",
    USER_PWD_ERROR: "Password does not match",

    GENRES_FETCH: "Genres fetch",
    GENRES_NOT_FOUND: "Genres does not found",
    GENRES_DELETE: "Genres has been deleted",
    GENRES_NOT_DELETE: "Genres not delete",
    GENRES_UPDATE: "Genres has been updated",
    GENRES_NOT_UPDATE: "Genres does not update",
    GENRES_ADD: "Genres has been created",
    GENRES_DUPLICATE: "Genres already exit",

    MOVIE_ROLE_FETCH: "Movie Role fetch",
    MOVIE_ROLE_NOT_FOUND: "Movie Role does not found",
    MOVIE_ROLE_DELETE: "Movie Role has been deleted",
    MOVIE_ROLE_NOT_DELETE: "Movie Role not delete",
    MOVIE_ROLE_UPDATE: "Movie Role has been updated",
    MOVIE_ROLE_NOT_UPDATE: "Movie Role does not update",
    MOVIE_ROLE_ADD: "Movie Role has been created",
    MOVIE_ROLE_DUPLICATE: "Movie Role already exit",

    MOVIE_FETCH: "Movie fetch",
    MOVIE_NOT_FOUND: "Movie does not found",
    MOVIE_DELETE: "Movie has been deleted",
    MOVIE_NOT_DELETE: "Movie not delete",
    MOVIE_UPDATE: "Movie has been updated",
    MOVIE_NOT_UPDATE: "Movie does not update",
    MOVIE_ADD: "Movie has been created",
    MOVIE_ADD_ERROR: "Movie can not created",
    MOVIE_DUPLICATE: "Movie already exit",

    PERSON_FETCH: "Data fetch",
    PERSON_NOT_FOUND: "Data does not found",
    PERSON_DELETE: "Data has been deleted",
    PERSON_NOT_DELETE: "Data not delete",
    PERSON_UPDATE: "Data has been updated",
    PERSON_NOT_UPDATE: "Data does not update",
    PERSON_ADD: "Data has been created",
    PERSON_ADD_ERROR: "Data can't added",
    PERSON_DUPLICATE: "Data already exit",

    DEPARTMENT_FETCH: "Department fetch",
    DEPARTMENT_NOT_FOUND: "Department does not found",
    DEPARTMENT_DELETE: "Department has been deleted",
    DEPARTMENT_NOT_DELETE: "Department not delete",
    DEPARTMENT_UPDATE: "Department has been updated",
    DEPARTMENT_NOT_UPDATE: "Department does not update",
    DEPARTMENT_ADD: "Department has been created",
    DEPARTMENT_DUPLICATE: "Department already exit",

}